export const ADD_PHOTOSHOOT_START   = "ADD_PHOTOSHOOT_START";
export const ADD_PHOTOSHOOT_SUCCESS = "ADD_PHOTOSHOOT_SUCCESS";
export const ADD_PHOTOSHOOT_ERROR   = "ADD_PHOTOSHOOT_ERROR";

export const UPDATE_PHOTOSHOOT_START   = "UPDATE_PHOTOSHOOT_START";
export const UPDATE_PHOTOSHOOT_SUCCESS = "UPDATE_PHOTOSHOOT_SUCCESS";
export const UPDATE_PHOTOSHOOT_ERROR   = "UPDATE_PHOTOSHOOT_ERROR";

