export const ADD_PHOTOSHOOT_START   = "ADD_PHOTOSHOOT_START";
export const ADD_PHOTOSHOOT_SUCCESS = "ADD_PHOTOSHOOT_SUCCESS";
export const ADD_PHOTOSHOOT_ERROR   = "ADD_PHOTOSHOOT_ERROR";

export const UPDATE_PHOTOSHOOT_START   = "UPDATE_PHOTOSHOOT_START";
export const UPDATE_PHOTOSHOOT_SUCCESS = "UPDATE_PHOTOSHOOT_SUCCESS";
export const UPDATE_PHOTOSHOOT_ERROR   = "UPDATE_PHOTOSHOOT_ERROR";

export const RETRIEVE_ALL_PHOTOSHOOTS_START   = "RETRIEVE_ALL_PHOTOSHOOTS_START";
export const RETRIEVE_ALL_PHOTOSHOOTS_SUCCESS = "RETRIEVE_ALL_PHOTOSHOOTS_SUCCESS";
export const RETRIEVE_ALL_PHOTOSHOOTS_ERROR   = "RETRIEVE_ALL_PHOTOSHOOTS_ERROR";

export const DELETE_PHOTOSHOOT_START   = "DELETE_PHOTOSHOOT_START";
export const DELETE_PHOTOSHOOT_SUCCESS = "DELETE_PHOTOSHOOT_SUCCESS";
export const DELETE_PHOTOSHOOT_ERROR   = "DELETE_PHOTOSHOOT_ERROR";
